/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bv_com_windows_jni_BVNativeJNI */

#ifndef _Included_org_bv_com_windows_jni_BVNativeJNI
#define _Included_org_bv_com_windows_jni_BVNativeJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bv_com_windows_jni_BVNativeJNI
 * Method:    ticks
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_org_bv_com_windows_jni_BVNativeJNI_ticks
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
