/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bv_com_vsam_jni_VSAMJNI */

#ifndef _Included_org_bv_com_vsam_jni_VSAMJNI
#define _Included_org_bv_com_vsam_jni_VSAMJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef org_bv_com_vsam_jni_VSAMJNI_TRUE
#define org_bv_com_vsam_jni_VSAMJNI_TRUE 1L
#undef org_bv_com_vsam_jni_VSAMJNI_FALSE
#define org_bv_com_vsam_jni_VSAMJNI_FALSE 0L
#undef org_bv_com_vsam_jni_VSAMJNI_RC_OK
#define org_bv_com_vsam_jni_VSAMJNI_RC_OK 0L
#undef org_bv_com_vsam_jni_VSAMJNI_RC_COMPLETE
#define org_bv_com_vsam_jni_VSAMJNI_RC_COMPLETE 1L
#undef org_bv_com_vsam_jni_VSAMJNI_RC_TIMEOUT
#define org_bv_com_vsam_jni_VSAMJNI_RC_TIMEOUT -1L
#undef org_bv_com_vsam_jni_VSAMJNI_QS_EQ
#define org_bv_com_vsam_jni_VSAMJNI_QS_EQ 0L
#undef org_bv_com_vsam_jni_VSAMJNI_QS_GT
#define org_bv_com_vsam_jni_VSAMJNI_QS_GT 1L
#undef org_bv_com_vsam_jni_VSAMJNI_QS_LT
#define org_bv_com_vsam_jni_VSAMJNI_QS_LT 2L
#undef org_bv_com_vsam_jni_VSAMJNI_QS_ASC
#define org_bv_com_vsam_jni_VSAMJNI_QS_ASC 3L
#undef org_bv_com_vsam_jni_VSAMJNI_QS_DSC
#define org_bv_com_vsam_jni_VSAMJNI_QS_DSC 4L
/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    getLastError
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_getLastError
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    open
 * Signature: (Lorg/bv/com/vsam/jni/Connection;JLorg/bv/com/vsam/jni/OpenOptions;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_open
  (JNIEnv *, jobject, jobject, jlong, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    openAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;JLorg/bv/com/vsam/jni/OpenOptions;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_openAsync
  (JNIEnv *, jobject, jobject, jlong, jobject, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    close
 * Signature: (Lorg/bv/com/vsam/jni/Connection;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_close
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    closeAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_closeAsync
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    createDatabase
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[BLorg/bv/com/vsam/jni/CreateDatabaseOptions;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_createDatabase
  (JNIEnv *, jobject, jobject, jint, jbyteArray, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    createDatabaseAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[BLorg/bv/com/vsam/jni/CreateDatabaseOptions;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_createDatabaseAsync
  (JNIEnv *, jobject, jobject, jint, jbyteArray, jobject, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    dropDatabase
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[B)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_dropDatabase
  (JNIEnv *, jobject, jobject, jint, jbyteArray);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    dropDatabaseAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[BLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_dropDatabaseAsync
  (JNIEnv *, jobject, jobject, jint, jbyteArray, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    createIndex
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[BLorg/bv/com/vsam/jni/CreateIndexOptions;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_createIndex
  (JNIEnv *, jobject, jobject, jint, jbyteArray, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    createIndexAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[BLorg/bv/com/vsam/jni/CreateIndexOptions;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_createIndexAsync
  (JNIEnv *, jobject, jobject, jint, jbyteArray, jobject, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    dropIndex
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[B)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_dropIndex
  (JNIEnv *, jobject, jobject, jint, jbyteArray);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    dropIndexAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[BLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_dropIndexAsync
  (JNIEnv *, jobject, jobject, jint, jbyteArray, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    autoCommit
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Z)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_autoCommit
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    autoCommitAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;ZLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_autoCommitAsync
  (JNIEnv *, jobject, jobject, jboolean, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    querySingle
 * Signature: (Lorg/bv/com/vsam/jni/Connection;IILjava/lang/Integer;Ljava/lang/Integer;[BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_querySingle
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jobject, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    querySingleAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;IILjava/lang/Integer;Ljava/lang/Integer;[BI[BI[BILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_querySingleAsync
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jobject, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryByDocumentId
 * Signature: (Lorg/bv/com/vsam/jni/Connection;IILjava/lang/Integer;Ljava/lang/Integer;[BLorg/bv/com/vsam/jni/DocumentId;I)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryByDocumentId
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jobject, jbyteArray, jobject, jint);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryByDocumentIdAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;IILjava/lang/Integer;Ljava/lang/Integer;[BLorg/bv/com/vsam/jni/DocumentId;ILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryByDocumentIdAsync
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jobject, jbyteArray, jobject, jint, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    query
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;I[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_query
  (JNIEnv *, jobject, jobject, jobject, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;I[BI[BIILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryAsync
  (JNIEnv *, jobject, jobject, jobject, jint, jbyteArray, jint, jbyteArray, jint, jint, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryNext
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;II[CLjava/lang/Integer;Ljava/lang/Integer;Lorg/bv/com/vsam/jni/DocumentId;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryNext
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jcharArray, jobject, jobject, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryNextAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;II[CLjava/lang/Integer;Ljava/lang/Integer;Lorg/bv/com/vsam/jni/DocumentId;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryNextAsync
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jcharArray, jobject, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryNextKey
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;II[CLorg/bv/com/vsam/jni/DocumentId;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryNextKey
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jcharArray, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryNextKeyAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;II[CLorg/bv/com/vsam/jni/DocumentId;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryNextKeyAsync
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jcharArray, jobject, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    update
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_update
  (JNIEnv *, jobject, jobject, jobject, jint, jstring, jint);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    updateAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;ILjava/lang/String;ILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_updateAsync
  (JNIEnv *, jobject, jobject, jobject, jint, jstring, jint, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    deleteResult
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_deleteResult
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    deleteResultAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_deleteResultAsync
  (JNIEnv *, jobject, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    delete
 * Signature: (Lorg/bv/com/vsam/jni/Connection;ILjava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_delete
  (JNIEnv *, jobject, jobject, jint, jstring, jint, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    deleteAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;ILjava/lang/String;ILjava/lang/String;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_deleteAsync
  (JNIEnv *, jobject, jobject, jint, jstring, jint, jstring, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    closeResult
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_closeResult
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    closeResultAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_closeResultAsync
  (JNIEnv *, jobject, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    write
 * Signature: (Lorg/bv/com/vsam/jni/Connection;ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_write
  (JNIEnv *, jobject, jobject, jint, jstring, jint);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    writeAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;ILjava/lang/String;ILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_writeAsync
  (JNIEnv *, jobject, jobject, jint, jstring, jint, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    commit
 * Signature: (Lorg/bv/com/vsam/jni/Connection;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_commit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    commitAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_commitAsync
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    rollback
 * Signature: (Lorg/bv/com/vsam/jni/Connection;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_rollback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    rollbackAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_rollbackAsync
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
