/* DO NOT EDIT THIS FILE - it is machine generated */
#include "Pch.h"
#include "org_bv_com_vsam_jni_vsamjni.h"
extern "C" {
/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    open
 * Signature: (Lorg/bv/com/vsam/jni/Connection;JLorg/bv/com/vsam/jni/OpenOptions;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_open
  (JNIEnv * env, jobject vsamJni, jobject connection, jlong timeout, jobject options) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    openAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;JLorg/bv/com/vsam/jni/OpenOptions;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_openAsync
  (JNIEnv * env, jobject, jobject, jlong, jobject, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    close
 * Signature: (Lorg/bv/com/vsam/jni/Connection;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_close
  (JNIEnv * env, jobject, jobject) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    closeAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_closeAsync
  (JNIEnv *env, jobject, jobject, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    createDatabase
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[BLorg/bv/com/vsam/jni/CreateDatabaseOptions;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_createDatabase
  (JNIEnv *env, jobject, jobject, jint, jbyteArray, jobject) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    createDatabaseAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[BLorg/bv/com/vsam/jni/CreateDatabaseOptions;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_createDatabaseAsync
  (JNIEnv *env, jobject, jobject, jint, jbyteArray, jobject, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    dropDatabase
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[B)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_dropDatabase
  (JNIEnv *env, jobject, jobject, jint, jbyteArray) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    dropDatabaseAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[BLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_dropDatabaseAsync
  (JNIEnv *env, jobject, jobject, jint, jbyteArray, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    createIndex
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[BLorg/bv/com/vsam/jni/CreateIndexOptions;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_createIndex
  (JNIEnv *env, jobject, jobject, jint, jbyteArray, jobject) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    createIndexAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[BLorg/bv/com/vsam/jni/CreateIndexOptions;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_createIndexAsync
  (JNIEnv *env, jobject, jobject, jint, jbyteArray, jobject, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    dropIndex
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[B)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_dropIndex
  (JNIEnv *env, jobject, jobject, jint, jbyteArray) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    dropIndexAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;I[BLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_dropIndexAsync
  (JNIEnv *env, jobject, jobject, jint, jbyteArray, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    autoCommit
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Z)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_autoCommit
  (JNIEnv *env, jobject, jobject, jboolean) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    autoCommitAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;ZLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_autoCommitAsync
  (JNIEnv *env, jobject, jobject, jboolean, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    querySingle
 * Signature: (Lorg/bv/com/vsam/jni/Connection;IILjava/lang/Integer;Ljava/lang/Integer;[BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_querySingle
  (JNIEnv *env, jobject, jobject, jint, jint, jobject, jobject, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    querySingleAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;IILjava/lang/Integer;Ljava/lang/Integer;[BI[BI[BILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_querySingleAsync
  (JNIEnv *env, jobject, jobject, jint, jint, jobject, jobject, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryByDocumentId
 * Signature: (Lorg/bv/com/vsam/jni/Connection;IILjava/lang/Integer;Ljava/lang/Integer;[BLorg/bv/com/vsam/jni/DocumentId;I)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryByDocumentId
  (JNIEnv *env, jobject, jobject, jint, jint, jobject, jobject, jbyteArray, jobject, jint) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryByDocumentIdAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;IILjava/lang/Integer;Ljava/lang/Integer;[BLorg/bv/com/vsam/jni/DocumentId;ILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryByDocumentIdAsync
  (JNIEnv *env, jobject, jobject, jint, jint, jobject, jobject, jbyteArray, jobject, jint, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    query
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;I[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_query
  (JNIEnv *env, jobject, jobject, jobject, jint, jbyteArray, jint, jbyteArray, jint, jint) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;I[BI[BIILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryAsync
  (JNIEnv *env, jobject, jobject, jobject, jint, jbyteArray, jint, jbyteArray, jint, jint, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryNext
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;II[CLjava/lang/Integer;Ljava/lang/Integer;Lorg/bv/com/vsam/jni/DocumentId;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryNext
  (JNIEnv *env, jobject, jobject, jobject, jint, jint, jcharArray, jobject, jobject, jobject) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryNextAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;II[CLjava/lang/Integer;Ljava/lang/Integer;Lorg/bv/com/vsam/jni/DocumentId;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryNextAsync
  (JNIEnv *env, jobject, jobject, jobject, jint, jint, jcharArray, jobject, jobject, jobject, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryNextKey
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;II[CLorg/bv/com/vsam/jni/DocumentId;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryNextKey
  (JNIEnv *env, jobject, jobject, jobject, jint, jint, jcharArray, jobject) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryNextKeyAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;II[CLorg/bv/com/vsam/jni/DocumentId;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryNextKeyAsync
  (JNIEnv *env, jobject, jobject, jobject, jint, jint, jcharArray, jobject, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    update
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_update
  (JNIEnv *env, jobject, jobject, jobject, jint, jstring, jint) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    updateAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;ILjava/lang/String;ILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_updateAsync
  (JNIEnv *env, jobject, jobject, jobject, jint, jstring, jint, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    deleteResult
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_deleteResult
  (JNIEnv *env, jobject, jobject, jobject) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    deleteResultAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_deleteResultAsync
  (JNIEnv *env, jobject, jobject, jobject, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    delete
 * Signature: (Lorg/bv/com/vsam/jni/Connection;ILjava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_delete
  (JNIEnv *env, jobject, jobject, jint, jstring, jint, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    deleteAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;ILjava/lang/String;ILjava/lang/String;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_deleteAsync
  (JNIEnv *env, jobject, jobject, jint, jstring, jint, jstring, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    closeResult
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_closeResult
  (JNIEnv *env, jobject, jobject, jobject) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    closeResultAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Lorg/bv/com/vsam/jni/ResultSet;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_closeResultAsync
  (JNIEnv *env, jobject, jobject, jobject, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    write
 * Signature: (Lorg/bv/com/vsam/jni/Connection;ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_write
  (JNIEnv *env, jobject, jobject, jint, jstring, jint) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    writeAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;ILjava/lang/String;ILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_writeAsync
  (JNIEnv *env, jobject, jobject, jint, jstring, jint, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    commit
 * Signature: (Lorg/bv/com/vsam/jni/Connection;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_commit
  (JNIEnv *env, jobject, jobject) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    commitAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_commitAsync
  (JNIEnv *env, jobject, jobject, jobject, jstring, jstring) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    rollback
 * Signature: (Lorg/bv/com/vsam/jni/Connection;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_rollback
  (JNIEnv *env, jobject, jobject) {
	return 0;
}

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    rollbackAsync
 * Signature: (Lorg/bv/com/vsam/jni/Connection;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_rollbackAsync
  (JNIEnv *env, jobject, jobject, jobject, jstring, jstring) {
	return 0;
}
}
