; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29336.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	__@@_PchSym_@00@UfhvihUqzxpwUvxorkhvRdliphkzxvUhbhgvnUhixUnzrmUxUgvnkxUdrmwldhUwvyftUkxsOlyq@4B2008FD98C1DD4
;	COMDAT __@@_PchSym_@00@UfhvihUqzxpwUvxorkhvRdliphkzxvUhbhgvnUhixUnzrmUxUgvnkxUdrmwldhUwvyftUkxsOlyq@4B2008FD98C1DD4
_BSS	SEGMENT
__@@_PchSym_@00@UfhvihUqzxpwUvxorkhvRdliphkzxvUhbhgvnUhixUnzrmUxUgvnkxUdrmwldhUwvyftUkxsOlyq@4B2008FD98C1DD4 DD 01H DUP (?)
_BSS	ENDS
msvcjmc	SEGMENT
__6CB86619_windows@pch DB 01H
__DA35BBA3_ctype@h DB 01H
__BDBF452D_basetsd@h DB 01H
__5ABB868E_corecrt_memcpy_s@h DB 01H
__813D228D_corecrt_memory@h DB 01H
__1D4384B7_corecrt_wstring@h DB 01H
__7989C355_string@h DB 01H
__113D6439_guiddef@h DB 01H
__D251E792_winnt@h DB 01H
__CCD5E0DD_processthreadsapi@h DB 01H
__C8C7AF0C_memoryapi@h DB 01H
__6457B4EF_winerror@h DB 01H
__DB0A31F1_winbase@h DB 01H
__B3E27A86_winuser@h DB 01H
__110C0647_stralign@h DB 01H
msvcjmc	ENDS
PUBLIC	__JustMyCode_Default
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
END
