/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bv_com_vsam_jni_VSAMJNI */

#ifndef _Included_org_bv_com_vsam_jni_VSAMJNI
#define _Included_org_bv_com_vsam_jni_VSAMJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef org_bv_com_vsam_jni_VSAMJNI_VERSION
#define org_bv_com_vsam_jni_VSAMJNI_VERSION 1L
#undef org_bv_com_vsam_jni_VSAMJNI_INDEX_CHAR_EBCDIC
#define org_bv_com_vsam_jni_VSAMJNI_INDEX_CHAR_EBCDIC 1L
#undef org_bv_com_vsam_jni_VSAMJNI_INDEX_CHAR_UTF8
#define org_bv_com_vsam_jni_VSAMJNI_INDEX_CHAR_UTF8 2L
#undef org_bv_com_vsam_jni_VSAMJNI_FORMAT_JSON
#define org_bv_com_vsam_jni_VSAMJNI_FORMAT_JSON 0L
#undef org_bv_com_vsam_jni_VSAMJNI_FORMAT_BSON
#define org_bv_com_vsam_jni_VSAMJNI_FORMAT_BSON 1L
#undef org_bv_com_vsam_jni_VSAMJNI_LOG_NONE
#define org_bv_com_vsam_jni_VSAMJNI_LOG_NONE 0L
#undef org_bv_com_vsam_jni_VSAMJNI_LOG_UNDO
#define org_bv_com_vsam_jni_VSAMJNI_LOG_UNDO 1L
#undef org_bv_com_vsam_jni_VSAMJNI_LOG_ALL
#define org_bv_com_vsam_jni_VSAMJNI_LOG_ALL 2L
#undef org_bv_com_vsam_jni_VSAMJNI_RC_OK
#define org_bv_com_vsam_jni_VSAMJNI_RC_OK 0L
#undef org_bv_com_vsam_jni_VSAMJNI_QS_EQ
#define org_bv_com_vsam_jni_VSAMJNI_QS_EQ 0L
#undef org_bv_com_vsam_jni_VSAMJNI_QS_GT
#define org_bv_com_vsam_jni_VSAMJNI_QS_GT 1L
#undef org_bv_com_vsam_jni_VSAMJNI_QS_LT
#define org_bv_com_vsam_jni_VSAMJNI_QS_LT 2L
#undef org_bv_com_vsam_jni_VSAMJNI_QS_ASC
#define org_bv_com_vsam_jni_VSAMJNI_QS_ASC 3L
#undef org_bv_com_vsam_jni_VSAMJNI_QS_DSC
#define org_bv_com_vsam_jni_VSAMJNI_QS_DSC 4L
/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    getLastError
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_getLastError
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    open
 * Signature: (Lorg/bv/com/vsam/jni/VSAMJNI/Connection;JLorg/bv/com/vsam/jni/VSAMJNI/OpenOptions;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_open
  (JNIEnv *, jobject, jobject, jlong, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    close
 * Signature: (Lorg/bv/com/vsam/jni/VSAMJNI/Connection;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_close
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    createDatabase
 * Signature: (Lorg/bv/com/vsam/jni/VSAMJNI/Connection;[BLorg/bv/com/vsam/jni/VSAMJNI/CreateDatabaseOptions;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_createDatabase
  (JNIEnv *, jobject, jobject, jbyteArray, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    dropDatabase
 * Signature: (Lorg/bv/com/vsam/jni/VSAMJNI/Connection;I[B)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_dropDatabase
  (JNIEnv *, jobject, jobject, jint, jbyteArray);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    createIndex
 * Signature: (Lorg/bv/com/vsam/jni/VSAMJNI/Connection;I[BLorg/bv/com/vsam/jni/VSAMJNI/CreateIndexOptions;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_createIndex
  (JNIEnv *, jobject, jobject, jint, jbyteArray, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    dropIndex
 * Signature: (Lorg/bv/com/vsam/jni/VSAMJNI/Connection;I[B)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_dropIndex
  (JNIEnv *, jobject, jobject, jint, jbyteArray);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    autoCommit
 * Signature: (Lorg/bv/com/vsam/jni/VSAMJNI/Connection;Z)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_autoCommit
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    querySingle
 * Signature: (Lorg/bv/com/vsam/jni/VSAMJNI/Connection;IILjava/lang/Integer;Ljava/lang/Integer;[BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_querySingle
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jobject, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    querySingleAsync
 * Signature: (Lorg/bv/com/vsam/jni/VSAMJNI/Connection;IILjava/lang/Integer;Ljava/lang/Integer;[BI[BI[BILorg/bv/com/vsam/jni/VSAMJNI;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_querySingleAsync
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jobject, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint, jobject, jstring, jstring);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    queryByDocumentId
 * Signature: (Lorg/bv/com/vsam/jni/VSAMJNI/Connection;IILjava/lang/Integer;Ljava/lang/Integer;[BLorg/bv/com/vsam/jni/VSAMJNI/DocumentId;I)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_queryByDocumentId
  (JNIEnv *, jobject, jobject, jint, jint, jobject, jobject, jbyteArray, jobject, jint);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    query
 * Signature: (Lorg/bv/com/vsam/jni/VSAMJNI/Connection;Lorg/bv/com/vsam/jni/VSAMJNI/ResultSet;I[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_query
  (JNIEnv *, jobject, jobject, jobject, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    commit
 * Signature: (Lorg/bv/com/vsam/jni/VSAMJNI/Connection;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_commit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_bv_com_vsam_jni_VSAMJNI
 * Method:    rollback
 * Signature: (Lorg/bv/com/vsam/jni/VSAMJNI/Connection;)I
 */
JNIEXPORT jint JNICALL Java_org_bv_com_vsam_jni_VSAMJNI_rollback
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
